name: Test Reporter with Notice Option
description: |
  Fork of dorny/test-reporter but with option to surface link to html notice to combat GHA bug 
author: Connor Vidlock <connor.vidlock@gmail.com>
inputs:
  artifact:
    description: Name or regex of artifact containing test results
    required: false
  name:
    description: Name of the check run
    required: true
  path:
    description: |
      Comma-separated list of paths to test results
      Supports wildcards via [fast-glob](https://github.com/mrmlnc/fast-glob)
      All matched result files must be of same format
    required: true
  path-replace-backslashes:
    description: |
      The fast-glob library that is internally used interprets backslashes as escape characters.
      If enabled, all backslashes in provided path will be replaced by forward slashes and act as directory separators.
      It might be useful when path input variable is composed dynamically from existing directory paths on Windows.
    default: 'false'
    required: false
  reporter:
    description: |
      Format of test results. Supported options:
        - dart-json
        - dotnet-trx
        - flutter-json
        - java-junit
        - jest-junit
        - mocha-json
        - swift-xunit
    required: true
  list-suites:
    description: |
      Limits which test suites are listed. Supported options:
        - all
        - only-failed
    required: false
    default: 'all'
  list-tests:
    description: |
      Limits which test cases are listed. Supported options:
        - all
        - only-failed
        - none
    required: false
    default: 'all'
  max-annotations:
    description: |
      Limits number of created annotations with error message and stack trace captured during test execution.
      Must be less or equal to 50.
    required: false
    default: '10'
  fail-on-error:
    description: Set this action as failed if test report contain any failed test
    required: false
    default: 'true'
  fail-on-empty:
    description: Set this action as failed if no test results were found
    required: true
    default: 'true'
  working-directory:
    description: Relative path under $GITHUB_WORKSPACE where the repository was checked out
    required: false
  show-html-notice:
    description: Show the link to the html results in the form of a notice on the summary page. This was created to combat a GHA bug of not always displaying the results in the right action.
    required: false
    default: 'false'
  only-summary:
    description: |
      Allows you to generate only the summary.
      If enabled, the report will contain a table listing each test results file and the number of passed, failed, and skipped tests.
      Detailed listing of test suites and test cases will be skipped.
    default: 'false'
    required: false
  token:
    description: GitHub Access Token
    required: false
    default: ${{ github.token }}
outputs:
  conclusion:
    description: |
      Final conclusion of the created check run:
        - 'success' if no failed tests was found
        - 'failure' if any failed test was found
  passed:
    description: Count of passed tests
  failed:
    description: Count of failed tests
  skipped:
    description: Count of skipped tests
  time:
    description: Test execution time [ms]
  runHtmlUrl:
    description: comma separated list of html links to test results
  url:
    description: Check run URL
  url_html:
    description: Check run URL HTML
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  color: blue
  icon: file-text
