name: Run all reports

on:
  pull_request:
    branches:
      - main
    paths-ignore: [ '**.md' ]
  push:
    paths-ignore: [ '**.md' ]
    branches:
      - main
  workflow_dispatch:

jobs:
  reports:
    name: Run
    runs-on: ubuntu-latest

    strategy:
      matrix:
        reporter: [ jest-junit, mocha-json, swift-xunit, dart-json, dotnet-trx, java-junit, flutter-json ]
        include:
          - reporter: jest-junit
            path: ./__tests__/fixtures/jest-junit.xml
          - reporter: mocha-json
            path: ./__tests__/fixtures/mocha-json.json
          - reporter: swift-xunit
            path: ./__tests__/fixtures/swift-xunit.xml
          - reporter: dart-json
            path: ./__tests__/fixtures/dart-json.json
          - reporter: dotnet-trx
            path: ./__tests__/fixtures/dotnet-trx.trx
          - reporter: java-junit
            path: ./__tests__/fixtures/external/java/pulsar-test-report.xml
          - reporter: flutter-json
            path: ./__tests__/fixtures/external/flutter/provider-test-results.json

    steps:
    - uses: actions/checkout@v4

    - uses: ./
      with:
        name: ${{ matrix.reporter }} report
        path: ${{ matrix.path }}
        reporter: ${{ matrix.reporter }}
        fail-on-error: false
